# Default values for claims-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: raeabbey1/imx-sample
  tag: "latest"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  name: claims-api
  type: ClusterIP
  port: 9950

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: claims.imx.com
      paths:
        - path: /api
          pathType: Prefix

claimsApiPort: 9950
mountPaths:
  dataSources: /opt/claims-api
  keys:
    public: /keys/public-key.pem
    private: /keys/private-key.pem

